### ISSUE TITLE
ModuleNotFoundError , I installed the packag, ran the sample code and got this error

### ISSUE THREAD

**Issue by harikrish-s** [Joooohan/audio-recorder-streamlit#2]
<img width="707" alt="Screenshot 2022-12-10 at 4 59 03 PM" src="https://user-images.githubusercontent.com/71437366/206852754-6f0e7610-47ed-469d-a5d5-fbc7999b91dc.png">

**Comment by Joooohan** [comment]
Hi @harikrish-s, do you still experience this issue ?
