### ISSUE TITLE
Stop Button Instead of Auto Detect Silence

### ISSUE THREAD

**Issue by chigkim** [Joooohan/audio-recorder-streamlit#24]
It's very cool to have auto detect for stop/pause. However, when dealing with multiple users, it's pretty impossible to target optimum threshold to accommodate multiple users because everyone has different microphone level, different room with different background noise, etc.

Could you provide an option to either have a separate stop button (with configurable label like send) or a toggle button (with configurable label speak/send) so that when the user click the button, it stops recording and processes the audio?

Thanks so much!

**Comment by Joooohan** [comment]
Hi, you can already stop the recording by clicking on the record button while the recording is ongoaing.

**Comment by chigkim** [comment]
Thanks, but how do you disable the auto stop so it records indefinitely until you click the button?

**Comment by Joooohan** [comment]
Just set a negative `energy_threshold` so that you are always above the threshold. This way the recorder will never stop automatically.
