### ISSUE TITLE
Hi dear friend.how can set time duration for recording and how to read audio file that saved?

### ISSUE THREAD

**Issue by drAliMollaei** [Joooohan/audio-recorder-streamlit#4]

**Comment by Joooohan** [comment]
Hi @drAliMollaei, I have just release a new version 0.0.8 that allows you to have a fixed recording length. See https://pypi.org/project/audio-recorder-streamlit/0.0.8/ in the FAQ section.

To save the audio_bytes to file, I think you can simply write them to a file.
```python
with open("file.wav", "wb") as f:
    f.write(audio_bytes)
```
