### ISSUE TITLE
Cannot import name 'audio_recorder' from 'audio_recorder_streamlit

### ISSUE THREAD

**Issue by lagarrueal** [Joooohan/audio-recorder-streamlit#6]
I've installed the package, and tried to use the sample code provided in the the README file, however, i'm facing this issue every time .
![image](https://user-images.githubusercontent.com/86953370/216305020-8316626b-6bcb-4176-af8a-9d7a149fa0c0.png)

**Comment by Joooohan** [comment]
Hi @lagarrueal, which version of streamlit and of the audio recorder are you using ?

**Comment by lagarrueal** [comment]
Hi, I'm currently running streamlit 1.17.0 and audio-recorder-streamlit 0.0.8.

**Comment by lagarrueal** [comment]
Hi, just a quick update, I actually got it working today. The only difference from the last time is that I'm running my web browser as admin and I have access to the microphone.

**Comment by Joooohan** [comment]
Ok, thanks for the update !

**Comment by zyb8543d** [comment]
Is this issue solved？ I have the same problem. my audio-recorder-streamlit version is 0.0.8,streamlit 1.15
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'audiorecorder' from 'audio_recorder_streamlit' (/home/ybZhang/miniconda3/lib/python3.8/site-packages/audio_recorder_streamlit/__init__.py)
```

**Comment by lagarrueal** [comment]
> Hi, just a quick update, I actually got it working today. The only difference from the last time is that I'm running my web browser as admin and I have access to the microphone. 

@v-yunbin I don't know if there is really an issue with this, just make sure to launch your browser as admin and that should do the job, at least it did for me.
